### PR TITLE
Support WSL2 in the wget cmd.

### PR DESCRIPTION
**Pull request by LarsBingBong**
This should work fine for other distros of Linux. Apparently on WSL2 `uname -o` returns: `GNU/Linux`

### CODE REVIEW

**Review by edznux-dd — APPROVED** [review]
LGTM, thanks!

**Comment by edznux-dd** [comment]
Sorry for the delay here, I'm working on resolving the issues with the system-tests worker.
I'll be merge as soon as it's resolved!

**Comment by d0g0x01** [comment]
Thanks for your contribution and sorry it took so long to merge. Moving from private to public broke a few pieces of our CI which this has now helped us fix

**Comment by LarsBingBong** [comment]
@d0g0x01 happy to help.

**Pull request merged**
